services:
  - type: web
    name: food-api
    env: node
    rootDir: food_api/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0